CREATE DATABASE _Telephone_diary;

USE _Telephone_diary;

CREATE TABLE DETAILS(
f_nAME VARCHAR(50),
l_nAME VARCHAR(50),
Type VARCHAR(50),
Number VARCHAR(11),
);


INSERT INTO DETAILS VALUES ('MUHAMMAD','FAHAD','OFFICE','03222520231');

SELECT * FROM DETAILS;